Repository nod-ai/shark-ai, pull requests merged in 2025-03, with the labels that each got.

#1078 Update sharded export command
  docs/shortfin/llm/user/llama_serving.md
Labels: documentation

#1076 Add `log_softmax` op to `shortfin.array`
  shortfin/python/array_host_ops.cc
  shortfin/python/shortfin/array/__init__.py
  shortfin/tests/api/array_ops_test.py
Labels: enhancement

#1065 Create abstract `BaseTokenSelectionStrategy` class for implementing different selection methods
  shortfin/python/shortfin_apps/llm/components/generate.py
  shortfin/python/shortfin_apps/llm/components/token_selection_strategy/__init__.py
  shortfin/python/shortfin_apps/llm/components/token_selection_strategy/base_token_selection_strategy.py
  shortfin/python/shortfin_apps/llm/components/token_selection_strategy/greedy_token_selection_strategy.py
  shortfin/requirements-tests.txt
  shortfin/tests/apps/llm/components/token_selection_strategy/conftest.py
  shortfin/tests/apps/llm/components/token_selection_strategy/greedy_token_selection_strategy_test.py
  shortfin/tests/apps/llm/components/token_selection_strategy/token_selection_strategy_test.py
  shortfin/tests/apps/llm/conftest.py
Labels: enhancement

#1163 refactored linux-mi300-1gpu-ossci to linux-mi300-1gpu-ossci-nod-ai
  .github/workflows/ci-llama-large-tests.yaml
  .github/workflows/ci-llama-quick-tests.yaml
  .github/workflows/ci-sdxl.yaml
  .github/workflows/ci-sglang-benchmark.yml
  .github/workflows/ci-sglang-integration-tests.yml
  .github/workflows/ci-sharktank-nightly.yml
  .github/workflows/ci-sharktank.yml
  .github/workflows/ci_eval_short.yaml
  .github/workflows/pkgci_shark_ai.yml
Labels: infra
